dotnet3.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Controllers/LookupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Benday.EasyAuthDemo.Api.ServiceLayers;
using Benday.EasyAuthDemo.Api.DomainModels;
using Benday.EasyAuthDemo.WebUi.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Benday.EasyAuthDemo.Api;
using Benday.Common;
using Microsoft.AspNetCore.Authorization;

namespace Benday.EasyAuthDemo.WebUi.Controllers
{
    [Authorize(Roles = "admin")]
    public class LookupController : Controller
    {
        private readonly IValidatorStrategy<LookupEditorViewModel> _Validator;
        private readonly ILookupService _LookupService;

        private readonly ILookupService _Service;

        public LookupController(ILookupService service,
            IValidatorStrategy<LookupEditorViewModel> validator)
        {
            if (service == null)
                throw new ArgumentNullException(nameof(service), "service is null.");

            if (validator == null)
            {
                throw new ArgumentNullException(nameof(validator), "Argument cannot be null.");
            }

            _Validator = validator;
            _Service = service;
            _LookupService = service;
        }

        public ActionResult Index()
        {
            var items = _Service.GetAll();

            return View(items);
        }

        [Route("/[controller]/[action]/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null || id.HasValue == false)
            {
                return new BadRequestResult();
            }

            var item = _Service.GetById(id.Value);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        public ActionResult Create()
        {
            return RedirectToAction("Edit", new { id = ApiConstants.UnsavedId });
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }

            Lookup item;
            LookupEditorViewModel viewModel;

            if (id.Value == ApiConstants.UnsavedId)
            {
                // create new
                viewModel = new LookupEditorViewModel();

                PopulateLookups(viewModel);
                return View(viewModel);
            }
            else
            {
                item = _Service.GetById(id.Value);

                if (item == null)
                {
                    return NotFound();
                }
                else
                {
                    viewModel = new LookupEditorViewModel();

                    var adapter = new LookupEditorViewModelAdapter();

                    adapter.Adapt(item, viewModel);

                    PopulateLookups(viewModel);
                }
            }

            return View(viewModel);
        }

        private void PopulateLookups(LookupEditorViewModel viewModel)
        {
            viewModel.LookupTypes = ToSelectListItems(
    _LookupService.GetAllByType("System.Lookup.Types"));
            viewModel.Statuses = ToSelectListItems(
                _LookupService.GetAllByType("System.Lookup.Status"));

        }

        private List<SelectListItem> ToSelectListItems(IList<Lookup> fromValues)
        {
            var toValues = new List<SelectListItem>();

            if (fromValues != null && fromValues.Count > 0)
            {
                foreach (var fromValue in fromValues)
                {
                    toValues.Add(new SelectListItem(
                        fromValue.LookupValue,
                        fromValue.LookupKey));
                }
            }

            return toValues;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LookupEditorViewModel item)
        {
            if (_Validator.IsValid(item) == true)
            {
                Lookup toValue;

                if (item.Id == ApiConstants.UnsavedId)
                {
                    toValue = new Lookup();
                }
                else
                {
                    toValue =
                        _Service.GetById(item.Id);

                    if (toValue == null)
                    {
                        return NotFound();
                    }
                }

                var adapter = new LookupEditorViewModelAdapter();

                adapter.Adapt(item, toValue);

                _Service.Save(toValue);

                return RedirectToAction("Edit", new { id = toValue.Id });
            }
            else
            {
                return View(item);
            }
        }

        public ActionResult Search()
        {
            var viewModel = new LookupSearchViewModel();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(LookupSearchViewModel item, string pageNumber, string sortBy)
        {
            if (item == null)
            {
                return View(new LookupSearchViewModel());
            }
            else if (item.IsSimpleSearch == true)
            {
                return RunSimpleSearch(item, pageNumber, sortBy);
            }
            else
            {
                return RunDetailedSearch(item, pageNumber, sortBy);
            }
        }

        private ActionResult RunDetailedSearch(LookupSearchViewModel item, string pageNumber, string sortBy)
        {
            var sortDirection = GetSortDirection(item, sortBy);

            ModelState.Clear();

            var results = _Service.Search(
searchValueLookupType: item.LookupType,
searchValueLookupKey: item.LookupKey,
searchValueLookupValue: item.LookupValue,
searchValueStatus: item.Status,
searchValueCreatedBy: item.CreatedBy,
searchValueLastModifiedBy: item.LastModifiedBy,


                sortBy: sortBy, sortByDirection: sortDirection);

            var pageableResults = new PageableResults<Lookup>();

            pageableResults.Initialize(results);

            pageableResults.CurrentPage = pageNumber.SafeToInt32(0);

            item.Results = pageableResults;
            item.CurrentSortDirection = sortDirection;
            item.CurrentSortProperty = sortBy;

            return View(item);
        }

        private ActionResult RunSimpleSearch(
            LookupSearchViewModel item, string pageNumber, string sortBy)
        {
            if (item.SimpleSearchValue.IsNullOrWhitespace() == false)
            {
                ModelState.Clear();

                string sortDirection;

                if (sortBy == null)
                {
                    // the value didn't change because of HTTP POST
                    sortBy = item.CurrentSortProperty;
                    sortDirection = item.CurrentSortDirection;
                }
                else
                {
                    sortDirection = GetSortDirection(item, sortBy);
                }

                var results = _Service.SimpleSearch(item.SimpleSearchValue,
                    sortBy, sortDirection);

                var pageableResults = new PageableResults<Lookup>();

                pageableResults.Initialize(results);

                pageableResults.CurrentPage = pageNumber.SafeToInt32(0);

                item.Results = pageableResults;
                item.CurrentSortDirection = sortDirection;
                item.CurrentSortProperty = sortBy;
            }

            return View(item);
        }


        private string GetSortDirection(ISortableResult viewModel, string sortBy)
        {
            if (String.IsNullOrWhiteSpace(sortBy) == true)
            {
                return SearchConstants.SortDirectionAscending;
            }
            else
            {
                if (String.Compare(sortBy, viewModel.CurrentSortProperty, true) == 0)
                {
                    if (viewModel.CurrentSortDirection == SearchConstants.SortDirectionAscending)
                    {
                        return SearchConstants.SortDirectionDescending;
                    }
                    else
                    {
                        return SearchConstants.SortDirectionAscending;
                    }
                }
                else
                {
                    return SearchConstants.SortDirectionAscending;
                }
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }

            Lookup item;

            item = _Service.GetById(id.Value);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Lookup item)
        {
            var deleteThis =
                _Service.GetById(item.Id);

            if (deleteThis == null)
            {
                return NotFound();
            }

            _Service.DeleteById(item.Id);

            return RedirectToAction("Index");
        }
    }
}

dotnet3.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Benday.EasyAuthDemo.Api.Security;
using Benday.EasyAuthDemo.WebUi.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace Benday.EasyAuthDemo.WebUi.Controllers
{
    public class SecurityController : Controller
    {
        private ISecurityConfiguration _Configuration;

        public SecurityController(ISecurityConfiguration configuration)
        {
            if (configuration == null)
            {
                throw new ArgumentNullException(nameof(configuration), $"{nameof(configuration)} is null.");
            }

            _Configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            var model = new SecurityLoginModel();

            if (_Configuration.AzureActiveDirectory == true)
            {
                AddLoginType(model, "Azure Active Directory", "aad");
            }

            if (_Configuration.MicrosoftAccount == true)
            {
                AddLoginType(model, "Microsoft Account", "microsoftaccount");
            }

            if (_Configuration.Google == true)
            {
                AddLoginType(model, "Google", "google");
            }

            if (_Configuration.DevelopmentMode == true)
            {
                AddLoginTypeKeyValue(model, "Local Development",
                    Url.Action("DevelopmentLogin"));
            }

            return View(model);
        }

        private string GetPostActionRedirectUri()
        {
            if (Request.Query.ContainsKey("ReturnUrl") == false)
            {
                return "/";
            }
            else
            {
                return Request.Query["ReturnUrl"];
            }
        }

        public IActionResult DevelopmentLogin()
        {
            if (_Configuration.DevelopmentMode == false)
            {
                return NotFound();
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> DevelopmentLogin(DevelopmentLoginModel model)
        {
            if (_Configuration.DevelopmentMode == false)
            {
                return NotFound();
            }
            else
            {
                var claims = new List<Claim>
                {
                    new Claim(SecurityConstants.Claim_X_MsClientPrincipalId, Guid.NewGuid().ToString()),
                    new Claim(
                        SecurityConstants.Claim_X_MsClientPrincipalIdp,
                        SecurityConstants.Idp_DevelopmentMode),
                    new Claim(SecurityConstants.Claim_X_MsClientPrincipalName, model.Username)
                };

                var temp = new ClaimsPrincipal(new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme));

                await HttpContext.SignInAsync(temp, new AuthenticationProperties
                {
                    IsPersistent = model.KeepMeLoggedIn,
                    AllowRefresh = true
                });

                return RedirectToAction("Index", "SecuritySummary");
            }
        }

        public async Task<IActionResult> Logout()
        {
            if (_Configuration.DevelopmentMode == false)
            {
                var easyAuthLogoutUrl = "/.auth/logout?post_logout_redirect_uri=" +
                    GetPostActionRedirectUri();

                return Redirect(easyAuthLogoutUrl);
            }
            else
            {
                await HttpContext.SignOutAsync();

                return RedirectToAction("Login");
            }
        }

        private void AddLoginType(SecurityLoginModel model, string displayName, string argName)
        {
            AddLoginTypeKeyValue(model, displayName, GetAuthUrlForProvider(argName));
        }

        private void AddLoginTypeKeyValue(SecurityLoginModel model, string key, string value)
        {
            if (model.LoginTypes == null)
            {
                model.LoginTypes = new List<KeyValuePair<string, string>>();
            }

            var temp = new KeyValuePair<string, string>(key, value);

            model.LoginTypes.Add(temp);
        }

        private string GetAuthUrlForProvider(string provider)
        {
            if (string.IsNullOrEmpty(provider))
            {
                throw new ArgumentException($"{nameof(provider)} is null or empty.", nameof(provider));
            }

            var temp = String.Format("/.auth/login/{0}?post_login_redirect_uri={1}",
                provider,
                GetPostActionRedirectUri());

            return temp;
        }
    }
}

dotnet3.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Views/Shared/_Layout.cshtml
@inject Benday.EasyAuthDemo.Api.Security.IUserInformation _UserInformation

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasyAuthDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Easy Auth Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lookup" asp-action="Index">lookup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SecuritySummary" asp-action="Index">security summary</a>
                        </li>
                        @if (_UserInformation.IsLoggedIn == false)
                        {
                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="Login">login</a></li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="Logout">logout</a></li>
                            <li class="navbar-text"><i>Hi, @_UserInformation.FirstName</i></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Benday.EasyAuthDemo.WebUi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

dotnet3.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Views/Shared/_PageableResultsControl.cshtml
@model IPageableResults

@Html.HiddenFor(model => model.CurrentPage)
<div class="row justify-content-between">
    <div >
        Row Count: @Model.TotalCount
    </div>
    <div >
        @for (var index = 1; index < Model.PageCount; index++)
        {
            @if (Model.CurrentPage == index)
            {
                <input type="submit" name="pageNumber" value="@index" class="btn btn-secondary" />
            }
            else
            {
                <input type="submit" name="pageNumber" value="@index" class="btn btn-light" />
            }
        }
    </div>
</div>