dotnet5.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Controllers/SecuritySummaryController.cs
using Benday.EasyAuthDemo.WebUi.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;

namespace Benday.EasyAuthDemo.WebUi.Controllers
{
    public class SecuritySummaryController : Controller
    {
        public IActionResult Index()
        {
            var model = new SecuritySummaryModel();

            var principal = this.User;

            if (principal == null)
            {
                model.IsClaimsPrincipalNull = true;
            }
            else
            {
                model.IsClaimsPrincipalNull = false;

                if (principal.Identity == null)
                {
                    model.IsPrimaryIdentityNull = true;
                }
                else
                {
                    model.IsPrimaryIdentityNull = false;
                    model.PrimaryIdentityAuthenticationType =
                        principal.Identity.AuthenticationType;
                    model.PrimaryIdentityIsAuthenticated =
                        principal.Identity.IsAuthenticated;
                    model.PrimaryIdentityName =
                        principal.Identity.Name;
                }
            }

            // principal.HasClaim()

            var identity = User.Identity;

            var claimsIdentityInstance =
                identity as ClaimsIdentity;

            if (claimsIdentityInstance == null)
            {
                model.Claims = new List<Claim>();
            }
            else
            {
                model.Claims =
                    claimsIdentityInstance.Claims.ToList();
            }

            if (principal.Identities == null ||
                principal.Identities.Count() == 0)
            {
                model.IdentitiesInfo = "Identities is null or 0 length.";
            }
            else
            {
                model.IdentitiesInfo = String.Format("Identities has '{0}' values",
                    principal.Identities.Count());

                model.Identities =
                    principal.Identities;
            }

            model.Headers = this.Request.Headers;

            model.Cookies = this.Request.Cookies;

            return View(model);
        }
    }
}

dotnet5.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Views/Shared/_Layout.cshtml
@inject Benday.EasyAuthDemo.Api.Security.IUserInformation _UserInformation
@inject Benday.EasyAuthDemo.Api.Security.ISecurityConfiguration _SecurityConfig

@inject Microsoft.Extensions.Configuration.IConfiguration _Configuration

@functions {
    private string GetVersionMessage()
    {
        var value = _Configuration["VersionMessage"];

        if (value == null)
        {
            return "(not set)";
        }
        else
        {
            return value;
        }
    }
}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>
        @ViewData["Title"] - Azure App Service Security Demo
        </title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    App Service Security Demo
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon">
                        </span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (_SecurityConfig.AuthType != Benday.EasyAuthDemo.Api.Security.SecurityConstants.AuthType_None)
                    {
                        <partial name="_LoginPartial" />
                    }
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">
                                person
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Lookup" asp-action="Index">
                                lookup
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">
                                user
                                </a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SecuritySummary"
                                asp-action="Index">security summary</a>
                        </li>
                        
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
            @RenderBody()
            </main>
        </div>
    
        <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Benjamin Day Consulting, Inc. | <a href="https://www.benday.com">www.benday.com</a> | <a
                href="https://www.github.com/benday-inc">github repos</a> | <i>Deployed: @(GetVersionMessage())</i>
        </div>
    </footer>
        <script src="~/lib/jquery/dist/jquery.min.js">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js">
        </script>
        <script src="~/js/site.js" asp-append-version="true">
        </script>
        <script src="~/js/template-row-table.js" asp-append-version="true">
        </script>
    @RenderSection("Scripts", required: false)
    </body>
</html>

dotnet5.0/Benday.EasyAuthDemo/src/Benday.EasyAuthDemo.WebUi/Views/Shared/_PageableResultsControl.cshtml
@model IPageableResults

@Html.HiddenFor(model => model.CurrentPage)
    <div class="row justify-content-between">
        <div >
        Row Count: @Model.TotalCount
        </div>
        <div >
        @for (var index = 1; index < Model.PageCount; index++)
        {
        @if (Model.CurrentPage == index)
        {
            <input type="submit" name="pageNumber" value="@index" class="btn btn-secondary" />
        }
        else
        {
            <input type="submit" name="pageNumber" value="@index" class="btn btn-light" />
        }
        }
        </div>
    </div>